language: java
sudo: false
install: true

# whitelist
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk8

script:
  - mvn package -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false